FLASK_DEBUG = True
FLASK_THREADED = True
FLASK_PORT = 3000
FLASK_HOST = "0.0.0.0"

RESTPLUS_SWAGGER_EXPANSION = "list"
RESTPLUS_VAL = True
RESTPLUS_MASK_SWAGGER = False

SQLALCHEMY_DATABASE_URI = "sqlite:///emails.db"
SQLALCHEMY_TRACK_MODS = False
